# Generated by Django 3.1.2 on 2020-12-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
